name: first site
favicon: null
layout_spectrum: 0.8417739858850837
typography_spectrum: 0.8251454057171941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e5e9'
    - '#000000'
    - '#4b5454'
    - '#bf4082'
    - '#fe0179'
  brandStrength: 0.9133470072411001
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.6621008322108537
purpose: []
